export const AI_MODELS = [
  {
    type: "model",
    name: "gpt-4o-mini",
    friendly_name: "OpenAI GPT-4o mini",
    model_family: "OpenAI",
    publisher: "OpenAI",
  },
  {
    type: "model",
    name: "gpt-4o",
    friendly_name: "OpenAI GPT-4o",
    model_family: "OpenAI",
    publisher: "OpenAI",
  },
  {
    type: "model",
    name: "o3-mini",
    friendly_name: "OpenAI o3-mini",
    model_family: "OpenAI",
    publisher: "OpenAI",
  },
  {
    type: "model",
    name: "o1",
    friendly_name: "OpenAI o1",
    model_family: "OpenAI",
    publisher: "OpenAI",
  },
  {
    type: "model",
    name: "o1-preview",
    friendly_name: "OpenAI o1-preview",
    model_family: "OpenAI",
    publisher: "OpenAI",
  },
  {
    type: "model",
    name: "o1-mini",
    friendly_name: "OpenAI o1-mini",
    model_family: "OpenAI",
    publisher: "OpenAI",
  },
  {
    type: "model",
    name: "Meta-Llama-3-1-8B-Instruct",
    friendly_name: "Meta-Llama-3.1-8B-Instruct",
    model_family: "Meta",
    publisher: "Meta",
  },
  {
    type: "model",
    name: "Meta-Llama-3-1-70B-Instruct",
    friendly_name: "Meta-Llama-3.1-70B-Instruct",
    model_family: "Meta",
    publisher: "Meta",
  },
  {
    type: "model",
    name: "Meta-Llama-3-1-405B-Instruct",
    friendly_name: "Meta-Llama-3.1-405B-Instruct",
    model_family: "Meta",
    publisher: "Meta",
  },
  {
    type: "model",
    name: "Llama-3-3-70B-Instruct",
    friendly_name: "Llama-3.3-70B-Instruct",
    model_family: "Meta",
    publisher: "Meta",
  },
  {
    type: "model",
    name: "Meta-Llama-3-70B-Instruct",
    friendly_name: "Meta-Llama-3-70B-Instruct",
    model_family: "Meta",
    publisher: "Meta",
  },
  {
    type: "model",
    name: "Meta-Llama-3-8B-Instruct",
    friendly_name: "Meta-Llama-3-8B-Instruct",
    model_family: "Meta",
    publisher: "Meta",
  },
  {
    type: "model",
    name: "Mistral-large-2407",
    friendly_name: "Mistral Large (2407)",
    model_family: "Mistral AI",
    publisher: "Mistral AI",
  },
  {
    type: "model",
    name: "Mistral-Nemo",
    friendly_name: "Mistral Nemo",
    model_family: "Mistral AI",
    publisher: "Mistral AI",
  },
  {
    type: "model",
    name: "Ministral-3B",
    friendly_name: "Ministral 3B",
    model_family: "Mistral AI",
    publisher: "Mistral AI",
  },
  {
    type: "model",
    name: "Mistral-large",
    friendly_name: "Mistral Large",
    model_family: "Mistral AI",
    publisher: "Mistral AI",
  },
  {
    type: "model",
    name: "Mistral-small",
    friendly_name: "Mistral Small",
    model_family: "Mistral AI",
    publisher: "Mistral AI",
  },
  {
    type: "model",
    name: "Codestral-2501",
    friendly_name: "Codestral 25.01",
    model_family: "Mistral AI",
    publisher: "Mistral AI",
  },
  {
    type: "model",
    name: "Mistral-Large-2411",
    friendly_name: "Mistral Large 24.11",
    model_family: "Mistral AI",
    publisher: "Mistral AI",
  },
  {
    type: "model",
    name: "Cohere-command-r-plus-08-2024",
    friendly_name: "Cohere Command R+ 08-2024",
    model_family: "Cohere",
    publisher: "Cohere",
  },
  {
    type: "model",
    name: "Cohere-command-r-08-2024",
    friendly_name: "Cohere Command R 08-2024",
    model_family: "Cohere",
    publisher: "Cohere",
  },
  {
    type: "model",
    name: "Cohere-command-r",
    friendly_name: "Cohere Command R",
    model_family: "Cohere",
    publisher: "Cohere",
  },
  {
    type: "model",
    name: "Cohere-command-r-plus",
    friendly_name: "Cohere Command R+",
    model_family: "Cohere",
    publisher: "Cohere",
  },
  {
    type: "model",
    name: "Phi-3-5-mini-instruct",
    friendly_name: "Phi-3.5-mini instruct (128k)",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-3-small-8k-instruct",
    friendly_name: "Phi-3-small instruct (8k)",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-3-small-128k-instruct",
    friendly_name: "Phi-3-small instruct (128k)",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-4-multimodal-instruct",
    friendly_name: "Phi-4-multimodal-instruct",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-4-mini-instruct",
    friendly_name: "Phi-4-mini-instruct",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-4",
    friendly_name: "Phi-4",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-3-mini-4k-instruct",
    friendly_name: "Phi-3-mini instruct (4k)",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-3-mini-128k-instruct",
    friendly_name: "Phi-3-mini instruct (128k)",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-3-medium-128k-instruct",
    friendly_name: "Phi-3-medium instruct (128k)",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-3-medium-4k-instruct",
    friendly_name: "Phi-3-medium instruct (4k)",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "Phi-3-5-MoE-instruct",
    friendly_name: "Phi-3.5-MoE instruct (128k)",
    model_family: "Microsoft",
    publisher: "Microsoft",
  },
  {
    type: "model",
    name: "DeepSeek-R1",
    friendly_name: "DeepSeek-R1",
    model_family: "DeepSeek",
    publisher: "DeepSeek",
  },
]

